apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: softdesign
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/teste-softdesign/teste-softdesign/app:v1
        resources:
          limits:
            cpu: "0.2"
            memory: "100Mi"
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: MONGO_URL